### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by stefgosselin** [tusharmakkar08/git-del-br#18]
Really enjoy this!   I do have a feature request, not sure if it is easily implementable.

It would be simply to have a --dry-run option that prints the branch that would be zapped.
 
I really want to use this at work it seems to work great on my personal projects, but I am afraid of running into a condition or even human mistake that would make me delete a branch that was wanted to keep.

Thanks mate.

**Comment by tusharmakkar08** [comment]
Hey @stefgosselin 

Glad you liked the tool 👍 

I think the feature what you are requesting is already implemented. You can use `-ls` (list) option similar to `--dry-run` option which you proposed. You can add `-ls` before any command and the branches won't be deleted eg:

        git-del-br -ls -l

Let me know if your requirement is different from that.

Thanks.
