### ISSUE TITLE
Matching by regular expression

### ISSUE THREAD

**Issue by owanturist** [tusharmakkar08/git-del-br#19]
Hello! Thank you for great tool!

When I tried to use `git-del-br` for clean a repo from useless branches I wanted to delete all branches except branches which started from `release/<version>` or `stable/<part_of_app>` etc. But I did not find a way for filter by **not** matching. Could you add opportunity for filter by regular expression? It should be very helpful.

Thanks!

**Comment by tusharmakkar08** [comment]
Hey @owanturist 

This sounds like a good feature addition. Will work on it soon. Meanwhile, if you are interested you can open a PR for the same.

Thanks

**Comment by tusharmakkar08** [comment]
Released the new version to pypi.
